### ISSUE TITLE
Set Smappee plug state to TREU/FALSE instead of ON/OFF

### ISSUE THREAD

**Issue by oberstel** [iobroker-community-adapters/ioBroker.smappee#25]
Enhancement Request:
This adapter sets pulg.x.state to ON / OFF instead of TRUE / FALSE.
ON / OFF can't be used in VIS or within SCENES, TRUE / FALSE would be more standard and more convenient.

Please consider changing this.

**Comment by forelleblau** [comment]
Since the state - object reads shows a string from smappee, I left this one as is.
But with v0.2.3 updates the switchON object with the state sent from smappee. So, you can use the switchON in vis as switch and as state-report. ok like this?

As an alternative I could introduce a 'stateBoleean' - object, that shows the state in true/false.
